exec-once = hyprpaper
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = quickshell
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOPexec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface accent-color 'orange'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Ember'
