preload = ~/dotfiles/wallpapers/Nocturne-of-Steel-and-Glass.jpg
preload = ~/dotfiles/wallpapers/1.png

wallpaper {
    monitor = DP-1
    path = ~/dotfiles/wallpapers/1.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/dotfiles/wallpapers/2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/dotfiles/wallpapers/1.png
    fit_mode = cover
}
